version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.6.0-browsers


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: mkdir -p reports

      - run:
          name: lint
          command: yarn lint --format junit --output-file reports/junit/lint.xml

      - run:
          name: unit test
          command: yarn test --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/unit-test.xml
            NODE_ENV: test

      - run:
          name: build
          command: yarn build
          environment:
            NODE_ENV: test

      - run:
          name: e2e test
          command: yarn -s test-e2e --reporter xunit > reports/junit/e2e.xml
          environment:
            NODE_ENV: test

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports
