version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.6.0


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          command: >
            mkdir -p ~/reports &&
            yarn lint -- --format junit --output-file ~/reports/eslint.xml
          when: always

      - run:
          command: >
            mkdir -p ~/reports &&
            JEST_JUNIT_OUTPUT=~/reports/jest.xml  yarn test --ci --testResultsProcessor="jest-junit"
          when: always

      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
