version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.6.0-browsers


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: mkdir -p ~/reports

      - run:
          name: lint
          command: yarn lint --format junit --output-file ~/reports/eslint.xml

      - run:
          name: unit test
          command: JEST_JUNIT_OUTPUT=~/reports/unit.xml  yarn test --ci --testResultsProcessor="jest-junit"

      - run:
          name: e2e test
          command: yarn test-e2e --reporter xunit > ~/reports/e2e.xml

      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
